apiVersion: v1
kind: Secret
metadata:
  name: llamaagent-secrets
  namespace: llamaagent
  labels:
    app: llamaagent
  annotations:
    # Reference external secret manager for production deployments
    # Example: external-secrets.io/backend: vault
    # Example: external-secrets.io/key-name: llamaagent/secrets
    kubernetes.io/description: "Secrets for LlamaAgent application"
type: Opaque
data:
  # Database connection string (base64 encoded)
  # Example: postgresql://user:pass@host:5432/llamaagent
  database-url: cG9zdGdyZXNxbDovL2xsYW1hYWdlbnQ6bGxhbWFhZ2VudEBwb3N0Z3Jlcy01NDMyL2xsYW1hYWdlbnQ=
  
  # JWT secret key for authentication (base64 encoded)
  jwt-secret: c3VwZXItc2VjcmV0LWp3dC1rZXktY2hhbmdlLWluLXByb2R1Y3Rpb24=
  
  # API keys should be managed externally in production
  # openai-api-key: <managed-externally>
  # anthropic-api-key: <managed-externally>
---
# ServiceAccount for the application
apiVersion: v1
kind: ServiceAccount
metadata:
  name: llamaagent
  namespace: llamaagent
  labels:
    app: llamaagent
automountServiceAccountToken: false