# LlamaAgent Cutting-Edge Configuration
# Advanced AI System with LiteLLM, Multimodal Reasoning, and Vision Capabilities

system:
  name: "LlamaAgent Advanced"
  version: "2.0.0"
  description: "Cutting-edge AI agent system with multimodal reasoning"
  author: "Nik Jois <nikjois@llamasearch.ai>"

# LiteLLM Universal Provider Configuration
litellm:
  # Budget and Cost Management
  budget:
    default_limit: 100.0
    daily_limit: 500.0
    currency: "USD"
    alert_threshold: 0.8
  
  # Auto Model Selection
  auto_selection:
    enabled: true
    prefer_local: false
    quality_threshold: 0.8
    cost_optimization: true
  
  # Cutting-Edge Models Configuration
  models:
    reasoning:
      primary: "deepseek-r1"
      fallback: "deepseek-r1-distilled"
      local_option: "ollama/deepseek-r1"
      
    vision:
      primary: "gpt-4o"
      fallback: "claude-3.5-sonnet"
      local_option: "ollama/llama3.2-vision:11b"
      
    function_calling:
      primary: "mistral-small-3.2"
      fallback: "gpt-4o"
      local_option: "ollama/mistral-small:3.2"
      
    multimodal:
      primary: "gpt-4o"
      fallback: "claude-3.5-sonnet"
      local_option: "ollama/qwen2-vl:7b"
      
    code:
      primary: "claude-3.5-sonnet"
      fallback: "deepseek-coder"
      local_option: "ollama/codellama:13b"

# Advanced Reasoning Configuration
reasoning:
  patterns:
    default: "chain_of_thought"
    available:
      - "chain_of_thought"
      - "tree_of_thoughts"
      - "self_reflection"
      - "iterative_refinement"
      - "multi_perspective"
  
  settings:
    max_iterations: 5
    confidence_threshold: 0.8
    enable_reflection: true
    thinking_depth: "deep"

# Multimodal Reasoning Configuration
multimodal:
  modes:
    default: "parallel"
    available:
      - "visual_first"
      - "text_first"
      - "parallel"
      - "chain_of_thought"
      - "reflection"
  
  vision:
    enabled: true
    max_image_size: "10MB"
    supported_formats: ["jpg", "png", "gif", "webp", "bmp"]
    analysis_depth: "comprehensive"
  
  cross_modal:
    enabled: true
    integration_mode: "deep"
    confidence_weighting: true

# Agent Orchestration Configuration
orchestration:
  multi_agent:
    enabled: true
    max_parallel: 5
    collaboration_patterns: true
    performance_tracking: true
  
  learning:
    enabled: true
    learning_rate: 0.1
    exploration_rate: 0.2
    memory_size: 1000
  
  specialties:
    - "reasoning"
    - "vision"
    - "code"
    - "research"
    - "creative"
    - "data_analysis"
    - "multimodal"

# API Configuration
api:
  host: "0.0.0.0"
  port: 8000
  cors:
    enabled: true
    origins: ["*"]
  
  endpoints:
    cutting_edge:
      - "/multimodal/analyze"
      - "/reasoning/advanced"
      - "/litellm/universal"
      - "/vision/analyze"
      - "/models/advanced"
      - "/orchestration/stats"
  
  rate_limiting:
    enabled: true
    requests_per_minute: 60
    burst_limit: 10

# Security Configuration
security:
  authentication:
    enabled: true
    method: "jwt"
    secret_key: "${JWT_SECRET_KEY}"
  
  input_validation:
    enabled: true
    max_prompt_length: 50000
    sanitization: true
  
  budget_protection:
    enabled: true
    per_user_limits: true
    alert_on_high_usage: true

# Database Configuration
database:
  type: "sqlite"  # or "postgresql"
  connection:
    sqlite:
      path: "data/llamaagent_advanced.db"
    postgresql:
      host: "${DB_HOST:-localhost}"
      port: "${DB_PORT:-5432}"
      database: "${DB_NAME:-llamaagent}"
      user: "${DB_USER}"
      password: "${DB_PASSWORD}"
  
  features:
    conversation_history: true
    reasoning_logs: true
    performance_metrics: true
    user_preferences: true

# Monitoring and Logging
monitoring:
  logging:
    level: "INFO"
    format: "structured"
    output: ["console", "file"]
    file_path: "logs/llamaagent.log"
  
  metrics:
    enabled: true
    prometheus: true
    custom_metrics:
      - "reasoning_quality"
      - "multimodal_success_rate"
      - "cost_per_interaction"
      - "user_satisfaction"
  
  health_checks:
    enabled: true
    interval: 60  # seconds
    endpoints: ["database", "llm_providers", "agents"]

# Development and Testing
development:
  debug_mode: false
  test_mode: false
  mock_providers: false
  
  testing:
    unit_tests: true
    integration_tests: true
    performance_tests: true
    load_tests: false

# Deployment Configuration
deployment:
  environment: "production"  # development, staging, production
  
  docker:
    enabled: true
    image: "llamaagent:advanced"
    resources:
      cpu: "2"
      memory: "4Gi"
      gpu: false  # Set to true if using local models
  
  scaling:
    auto_scaling: true
    min_replicas: 1
    max_replicas: 10
    target_cpu: 70
  
  health_check:
    path: "/health"
    port: 8000
    initial_delay: 30
    period: 10

# Feature Flags
features:
  cutting_edge_models: true
  multimodal_reasoning: true
  advanced_thinking: true
  vision_analysis: true
  agent_orchestration: true
  real_time_streaming: true
  local_model_support: true
  budget_optimization: true
  self_improvement: true
  research_integration: true

# External Integrations
integrations:
  ollama:
    enabled: true
    base_url: "http://localhost:11434"
    models: ["llama3.2-vision:11b", "qwen2-vl:7b", "deepseek-r1", "mistral-small:3.2"]
  
  openai:
    enabled: true
    api_key: "${OPENAI_API_KEY}"
    models: ["gpt-4o", "gpt-4o-mini", "text-embedding-3-small"]
  
  anthropic:
    enabled: true
    api_key: "${ANTHROPIC_API_KEY}"
    models: ["claude-3-5-sonnet-20241022", "claude-3-haiku-20240307"]
  
  mistral:
    enabled: true
    api_key: "${MISTRAL_API_KEY}"
    models: ["mistral-small-3.2-24b-instruct"]
  
  deepseek:
    enabled: true
    api_key: "${DEEPSEEK_API_KEY}"
    models: ["deepseek-r1", "deepseek-r1-distilled-llama-8b"]

# Research and Innovation Settings
research:
  experimental_features: true
  cutting_edge_research: true
  
  areas:
    - "vision_reasoning"
    - "cross_modal_understanding"
    - "advanced_thinking_patterns"
    - "self_improving_agents"
    - "dynamic_orchestration"
    - "budget_aware_optimization"
  
  innovation_mode:
    enabled: true
    risk_tolerance: "medium"
    adaptation_speed: "fast" 