apiVersion: v2
name: llamaagent
description: Advanced Multi-Agent AI Framework with Task Planning, Research Capabilities, and Agent Spawning
type: application
version: 1.0.0
appVersion: "1.0.0"
home: https://github.com/nikjois/llamaagent
sources:
  - https://github.com/nikjois/llamaagent
maintainers:
  - name: Nik Jois
    email: nikjois@llamasearch.ai
keywords:
  - ai
  - agents
  - llm
  - task-planning
  - research
  - agent-spawning
  - python
  - production-ready
annotations:
  category: AI/ML
dependencies:
  - name: postgresql
    version: "12.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: "17.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: prometheus
    version: "19.x.x"
    repository: https://prometheus-community.github.io/helm-charts
    condition: monitoring.prometheus.enabled
  - name: grafana
    version: "6.x.x"
    repository: https://grafana.github.io/helm-charts
    condition: monitoring.grafana.enabled