apiVersion: apps/v1
kind: Deployment
metadata:
  name: llamaagent-api
spec:
  replicas: 5
  template:
    spec:
      containers:
      - name: api
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "4000m"
        env:
        - name: ENV
          value: "production"
        - name: LOG_LEVEL
          value: "info"
        - name: WORKERS
          value: "8"
        - name: ENABLE_PROFILING
          value: "false"
        - name: ENABLE_DEBUG
          value: "false"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - llamaagent-api
            topologyKey: kubernetes.io/hostname
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: node-role.kubernetes.io/compute
                operator: In
                values:
                - "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llamaagent-worker
spec:
  replicas: 10
  template:
    spec:
      containers:
      - name: worker
        resources:
          requests:
            memory: "4Gi"
            cpu: "2000m"
          limits:
            memory: "8Gi"
            cpu: "8000m"
        env:
        - name: WORKER_CONCURRENCY
          value: "20"
        - name: WORKER_PREFETCH
          value: "2"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - llamaagent-worker
              topologyKey: kubernetes.io/hostname
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llamaagent-multimodal-worker
spec:
  replicas: 4
  template:
    spec:
      containers:
      - name: worker
        resources:
          requests:
            memory: "8Gi"
            cpu: "4000m"
            nvidia.com/gpu: 1
          limits:
            memory: "16Gi"
            cpu: "8000m"
            nvidia.com/gpu: 1
      nodeSelector:
        accelerator: nvidia-tesla-v100
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule