apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: llamaagent-api-hpa
spec:
  minReplicas: 5
  maxReplicas: 50
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  - type: Pods
    pods:
      metric:
        name: http_requests_per_second
      target:
        type: AverageValue
        averageValue: "200"
  - type: External
    external:
      metric:
        name: response_time_95th_percentile
      target:
        type: Value
        value: "500m"  # 500ms
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: llamaagent-worker-hpa
spec:
  minReplicas: 10
  maxReplicas: 100
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  - type: External
    external:
      metric:
        name: redis_queue_length
        selector:
          matchLabels:
            queue: evolution_tasks
      target:
        type: AverageValue
        averageValue: "5"
  - type: External
    external:
      metric:
        name: average_task_processing_time
      target:
        type: Value
        value: "30s"