apiVersion: v1
kind: ServiceAccount
metadata:
  name: llamaagent-api
  namespace: llamaagent
  labels:
    app: llamaagent
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: llamaagent-worker
  namespace: llamaagent
  labels:
    app: llamaagent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: llamaagent-api-role
  namespace: llamaagent
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: llamaagent-worker-role
  namespace: llamaagent
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: llamaagent-api-rolebinding
  namespace: llamaagent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: llamaagent-api-role
subjects:
- kind: ServiceAccount
  name: llamaagent-api
  namespace: llamaagent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: llamaagent-worker-rolebinding
  namespace: llamaagent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: llamaagent-worker-role
subjects:
- kind: ServiceAccount
  name: llamaagent-worker
  namespace: llamaagent