name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt || pip install pytest black isort flake8
    - name: Run tests
      run: pytest tests/unit/ -v --disable-warnings
    - name: Check code style
      run: |
        black --check . || echo "Black formatting check failed but continuing"
        isort --check-only . || echo "isort check failed but continuing"
        flake8 . || echo "flake8 check failed but continuing" 